- job:
    name: 'infra-project-config-check'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 10
        - timestamps
        - ansicolor

    builders:
        - revoke-sudo
        - gerrit-git-prep
        - yaml-verifyall
        - jjb-check

- job:
    name: 'infra-project-config-gate'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 10
        - timestamps
        - ansicolor

    builders:
        - revoke-sudo
        - gerrit-git-prep
        - yaml-verifyall
