- job-template:
    name: 'ops-config-yaml-check-{platform}'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor

    builders:
        - revoke-sudo
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: '{platform}'

- job-template:
    name: 'ops-config-yaml-gate-{platform}'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor

    builders:
        - revoke-sudo
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: '{platform}'

- job-group:
    name: 'ops-config-yaml-jobs'
    jobs:
      - 'ops-config-yaml-check-{platform}'
      - 'ops-config-yaml-gate-{platform}'
