- job:
    name: 'ops-config-yaml-check-as5712'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor

    builders:
        - revoke-sudo
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: 'as5712'

- job:
    name: 'ops-config-yaml-check-genericx86-64'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor

    builders:
        - revoke-sudo
        - module-build-branch:
            module: 'ops-config-yaml'
            platform: 'genericx86-64'

- job:
    name: 'ops-config-yaml-gate-as5712'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor

    builders:
        - module-build:
            module: 'ops-config-yaml'
            platform: 'as5712'

- job:
    name: 'ops-config-yaml-gate-genericx86-64'
    node: vsi

    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor

    builders:
        - module-build:
            module: 'ops-config-yaml'
            platform: 'genericx86-64'
        - module-cttest:
            module: 'ops-config-yaml'
            platform: 'genericx86-64'

    publishers:
        - junit:
            results: 'build/*test*.xml'
