- job-template:
    name: 'ops-config-as571-check-{platform}'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor

    builders:
        - revoke-sudo
        - module-build:
            module: 'ops-config-as571'
            platform: '{platform}'

- job-template:
    name: 'ops-config-as571-gate-{platform}'
    node: openswitch

    wrappers:
        - build-timeout:
            timeout: 120
        - timestamps
        - ansicolor

    builders:
        - revoke-sudo
        - module-build:
            module: 'ops-config-as571'
            platform: '{platform}'

- job-group:
    name: 'ops-config-as571-jobs'
    jobs:
      - 'ops-config-as571-check-{platform}'
      - 'ops-config-as571-gate-{platform}'
